const data = [
    {
        "idMeal": "52858",
        "strMeal": "New York cheesecake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "American",
        "strInstructions": "Position an oven shelf in the middle of the oven. Preheat the oven to fan 160C/conventional 180C/gas 4. Line the base of a 23cm springform cake tin with parchment paper. For the crust, melt the butter in a medium pan. Stir in the biscuit crumbs and sugar so the mixture is evenly moistened. Press the mixture into the bottom of the pan and bake for 10 minutes. Cool on a wire rack while preparing the filling.\r\nFor the filling, increase the oven temperature to fan 200C/conventional 240C/gas 9. In a table top mixer fitted with the paddle attachment, beat the soft cheese at medium-low speed until creamy, about 2 minutes. With the mixer on low, gradually add the sugar, then the flour and a pinch of salt, scraping down the sides of the bowl and the paddle twice.\r\nSwap the paddle attachment for the whisk. Continue by adding the vanilla, lemon zest and juice. Whisk in the eggs and yolk, one at a time, scraping the bowl and whisk at least twice. Stir the 284ml carton of soured cream until smooth, then measure 200ml/7fl oz (just over 3⁄4 of the carton). Continue on low speed as you add the measured soured cream (reserve the rest). Whisk to blend, but don't over-beat. The batter should be smooth, light and somewhat airy.\r\nBrush the sides of the springform tin with melted butter and put on a baking sheet. Pour in the filling - if there are any lumps, sink them using a knife - the top should be as smooth as possible. Bake for 10 minutes. Reduce oven temperature to fan 90C/conventional 110C/gas 1⁄4 and bake for 25 minutes more. If you gently shake the tin, the filling should have a slight wobble. Turn off the oven and open the oven door for a cheesecake that's creamy in the centre, or leave it closed if you prefer a drier texture. Let cool in the oven for 2 hours. The cheesecake may get a slight crack on top as it cools.\r\nCombine the reserved soured cream with the 142ml carton, the sugar and lemon juice for the topping. Spread over the cheesecake right to the edges. Cover loosely with foil and refrigerate for at least 8 hours or overnight.\r\nRun a round-bladed knife around the sides of the tin to loosen any stuck edges. Unlock the side, slide the cheesecake off the bottom of the tin onto a plate, then slide the parchment paper out from underneath.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/swttys1511385853.jpg",
        "strTags": "Desert,Dairy,Pudding,Cake,Breakfast",
        "strYoutube": "https://www.youtube.com/watch?v=tspdJ6hxqnc",
        "strIngredient1": "Butter",
        "strIngredient2": "Sour Cream",
        "strIngredient3": "Sugar",
        "strIngredient4": "Cream Cheese",
        "strIngredient5": "Caster Sugar",
        "strIngredient6": "Plain Flour",
        "strIngredient7": "Lemon Juice",
        "strIngredient8": "Eggs",
        "strIngredient9": "Sour Cream",
        "strIngredient10": "Sour Cream",
        "strIngredient11": "Caster Sugar",
        "strIngredient12": "Lemon Juice",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "85g",
        "strMeasure2": "140g",
        "strMeasure3": "1tbsp",
        "strMeasure4": "900g",
        "strMeasure5": "250g",
        "strMeasure6": "3 tbs",
        "strMeasure7": "1 ½ teaspoons",
        "strMeasure8": "3 Large",
        "strMeasure9": "250ml",
        "strMeasure10": "150ml",
        "strMeasure11": "1 tbsp",
        "strMeasure12": "2 tsp",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/2869/new-york-cheesecake",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "53007",
        "strMeal": "Honey Yogurt Cheesecake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "Greek",
        "strInstructions": "Heat oven to 160C/140C fan/gas 3. Crush the biscuits and most of the almonds inside a plastic food bag using a rolling pin. Mix with the butter, then press into the bottom of a deep, oval, 23cm dish (or something similar in size – a roasting tin, baking dish or cake tin will work). Bake for 10 mins until crisp.\r\n\r\nStir or mash together the yogurt and mascarpone, then whisk in the eggs, one at a time. Stir in the lemon and orange zests, then stir in most of the honey, reserving about 3 tbsp. Spread over the biscuit base, cover loosely with foil and cook for 1 hr. Remove the foil and cook for 15 mins more until lightly golden and the top is firm with just the slightest wobble in the middle. Leave to cool. Can be kept in the fridge for up to 2 days.\r\n\r\nTo serve, scatter with almonds, drizzle over the remaining honey, and hand around fresh fruit to go with it.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/y2irzl1585563479.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=JE8crtueXs8",
        "strIngredient1": "Digestive Biscuits",
        "strIngredient2": "Almonds",
        "strIngredient3": "Butter",
        "strIngredient4": "Greek Yogurt",
        "strIngredient5": "Mascarpone",
        "strIngredient6": "Eggs",
        "strIngredient7": "Lemon",
        "strIngredient8": "Orange",
        "strIngredient9": "Honey",
        "strIngredient10": "Fruit Mix",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "100g ",
        "strMeasure2": "85g",
        "strMeasure3": "85g",
        "strMeasure4": "250ml",
        "strMeasure5": "750g",
        "strMeasure6": "2",
        "strMeasure7": "Zest of 1",
        "strMeasure8": "Zest of 1",
        "strMeasure9": "250ml",
        "strMeasure10": "To serve",
        "strMeasure11": " ",
        "strMeasure12": " ",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "https://www.bbcgoodfood.com/recipes/honey-yogurt-cheesecake",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "52861",
        "strMeal": "Peanut Butter Cheesecake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "American",
        "strInstructions": "Oil and line a 20cm round loose- bottomed cake tin with cling film, making it as smooth as possible. Melt the butter in a pan. Crush the biscuits by bashing them in a bag with a rolling pin, then stir them into the butter until very well coated. Press the mixture firmly into the base of the tin and chill.\r\nSoak the gelatine in water while you make the filling. Tip the ricotta into a bowl, then beat in the peanut butter and syrup. Ricotta has a slightly grainy texture so blitz until smooth with a stick blender for a smoother texture if you prefer.\r\nTake the soaked gelatine from the water and squeeze dry. Put it into a pan with the milk and heat very gently until the gelatine dissolves. Beat into the peanut mixture, then tip onto the biscuit base. Chill until set.\r\nTo freeze, leave in the tin and as soon as it is solid, cover the surface with cling film, then wrap the tin with cling film and foil.\r\nTo defrost, thaw in the fridge overnight.\r\nTo serve, carefully remove from the tin. Whisk the cream with the sugar until it holds its shape, then spread on top of the cheesecake and scatter with the peanut brittle.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/qtuuys1511387068.jpg",
        "strTags": "Cake,Desert,Treat,UnHealthy,Speciality",
        "strYoutube": "https://www.youtube.com/watch?v=QSTsturcyL0",
        "strIngredient1": "Butter",
        "strIngredient2": "Peanut Cookies",
        "strIngredient3": "Gelatine Leafs",
        "strIngredient4": "Ricotta",
        "strIngredient5": "Peanut Butter",
        "strIngredient6": "Golden Syrup",
        "strIngredient7": "Milk",
        "strIngredient8": "Double Cream",
        "strIngredient9": "Light Brown Soft Sugar",
        "strIngredient10": "Peanut Brittle",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "50g",
        "strMeasure2": "175g",
        "strMeasure3": "5",
        "strMeasure4": "500g",
        "strMeasure5": "175g",
        "strMeasure6": "175g",
        "strMeasure7": "150ml",
        "strMeasure8": "275ml",
        "strMeasure9": "2 tblsp ",
        "strMeasure10": "Crushed",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/1759649/peanut-butter-cheesecake",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "528612",
        "strMeal": "Peanut Butter Cheesecake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "American",
        "strInstructions": "Oil and line a 20cm round loose- bottomed cake tin with cling film, making it as smooth as possible. Melt the butter in a pan. Crush the biscuits by bashing them in a bag with a rolling pin, then stir them into the butter until very well coated. Press the mixture firmly into the base of the tin and chill.\r\nSoak the gelatine in water while you make the filling. Tip the ricotta into a bowl, then beat in the peanut butter and syrup. Ricotta has a slightly grainy texture so blitz until smooth with a stick blender for a smoother texture if you prefer.\r\nTake the soaked gelatine from the water and squeeze dry. Put it into a pan with the milk and heat very gently until the gelatine dissolves. Beat into the peanut mixture, then tip onto the biscuit base. Chill until set.\r\nTo freeze, leave in the tin and as soon as it is solid, cover the surface with cling film, then wrap the tin with cling film and foil.\r\nTo defrost, thaw in the fridge overnight.\r\nTo serve, carefully remove from the tin. Whisk the cream with the sugar until it holds its shape, then spread on top of the cheesecake and scatter with the peanut brittle.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/qtuuys1511387068.jpg",
        "strTags": "Cake,Desert,Treat,UnHealthy,Speciality",
        "strYoutube": "https://www.youtube.com/watch?v=QSTsturcyL0",
        "strIngredient1": "Butter",
        "strIngredient2": "Peanut Cookies",
        "strIngredient3": "Gelatine Leafs",
        "strIngredient4": "Ricotta",
        "strIngredient5": "Peanut Butter",
        "strIngredient6": "Golden Syrup",
        "strIngredient7": "Milk",
        "strIngredient8": "Double Cream",
        "strIngredient9": "Light Brown Soft Sugar",
        "strIngredient10": "Peanut Brittle",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "50g",
        "strMeasure2": "175g",
        "strMeasure3": "5",
        "strMeasure4": "500g",
        "strMeasure5": "175g",
        "strMeasure6": "175g",
        "strMeasure7": "150ml",
        "strMeasure8": "275ml",
        "strMeasure9": "2 tblsp ",
        "strMeasure10": "Crushed",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/1759649/peanut-butter-cheesecake",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }
    ,
    {
        "idMeal": "528261",
        "strMeal": "Peanut Butter Cheesecake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "American",
        "strInstructions": "Oil and line a 20cm round loose- bottomed cake tin with cling film, making it as smooth as possible. Melt the butter in a pan. Crush the biscuits by bashing them in a bag with a rolling pin, then stir them into the butter until very well coated. Press the mixture firmly into the base of the tin and chill.\r\nSoak the gelatine in water while you make the filling. Tip the ricotta into a bowl, then beat in the peanut butter and syrup. Ricotta has a slightly grainy texture so blitz until smooth with a stick blender for a smoother texture if you prefer.\r\nTake the soaked gelatine from the water and squeeze dry. Put it into a pan with the milk and heat very gently until the gelatine dissolves. Beat into the peanut mixture, then tip onto the biscuit base. Chill until set.\r\nTo freeze, leave in the tin and as soon as it is solid, cover the surface with cling film, then wrap the tin with cling film and foil.\r\nTo defrost, thaw in the fridge overnight.\r\nTo serve, carefully remove from the tin. Whisk the cream with the sugar until it holds its shape, then spread on top of the cheesecake and scatter with the peanut brittle.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/qtuuys1511387068.jpg",
        "strTags": "Cake,Desert,Treat,UnHealthy,Speciality",
        "strYoutube": "https://www.youtube.com/watch?v=QSTsturcyL0",
        "strIngredient1": "Butter",
        "strIngredient2": "Peanut Cookies",
        "strIngredient3": "Gelatine Leafs",
        "strIngredient4": "Ricotta",
        "strIngredient5": "Peanut Butter",
        "strIngredient6": "Golden Syrup",
        "strIngredient7": "Milk",
        "strIngredient8": "Double Cream",
        "strIngredient9": "Light Brown Soft Sugar",
        "strIngredient10": "Peanut Brittle",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "50g",
        "strMeasure2": "175g",
        "strMeasure3": "5",
        "strMeasure4": "500g",
        "strMeasure5": "175g",
        "strMeasure6": "175g",
        "strMeasure7": "150ml",
        "strMeasure8": "275ml",
        "strMeasure9": "2 tblsp ",
        "strMeasure10": "Crushed",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/1759649/peanut-butter-cheesecake",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "522861",
        "strMeal": "Peanut Butter Cheesecake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "American",
        "strInstructions": "Oil and line a 20cm round loose- bottomed cake tin with cling film, making it as smooth as possible. Melt the butter in a pan. Crush the biscuits by bashing them in a bag with a rolling pin, then stir them into the butter until very well coated. Press the mixture firmly into the base of the tin and chill.\r\nSoak the gelatine in water while you make the filling. Tip the ricotta into a bowl, then beat in the peanut butter and syrup. Ricotta has a slightly grainy texture so blitz until smooth with a stick blender for a smoother texture if you prefer.\r\nTake the soaked gelatine from the water and squeeze dry. Put it into a pan with the milk and heat very gently until the gelatine dissolves. Beat into the peanut mixture, then tip onto the biscuit base. Chill until set.\r\nTo freeze, leave in the tin and as soon as it is solid, cover the surface with cling film, then wrap the tin with cling film and foil.\r\nTo defrost, thaw in the fridge overnight.\r\nTo serve, carefully remove from the tin. Whisk the cream with the sugar until it holds its shape, then spread on top of the cheesecake and scatter with the peanut brittle.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/qtuuys1511387068.jpg",
        "strTags": "Cake,Desert,Treat,UnHealthy,Speciality",
        "strYoutube": "https://www.youtube.com/watch?v=QSTsturcyL0",
        "strIngredient1": "Butter",
        "strIngredient2": "Peanut Cookies",
        "strIngredient3": "Gelatine Leafs",
        "strIngredient4": "Ricotta",
        "strIngredient5": "Peanut Butter",
        "strIngredient6": "Golden Syrup",
        "strIngredient7": "Milk",
        "strIngredient8": "Double Cream",
        "strIngredient9": "Light Brown Soft Sugar",
        "strIngredient10": "Peanut Brittle",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "50g",
        "strMeasure2": "175g",
        "strMeasure3": "5",
        "strMeasure4": "500g",
        "strMeasure5": "175g",
        "strMeasure6": "175g",
        "strMeasure7": "150ml",
        "strMeasure8": "275ml",
        "strMeasure9": "2 tblsp ",
        "strMeasure10": "Crushed",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/1759649/peanut-butter-cheesecake",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "528161",
        "strMeal": "Peanut Butter Cheesecake",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "American",
        "strInstructions": "Oil and line a 20cm round loose- bottomed cake tin with cling film, making it as smooth as possible. Melt the butter in a pan. Crush the biscuits by bashing them in a bag with a rolling pin, then stir them into the butter until very well coated. Press the mixture firmly into the base of the tin and chill.\r\nSoak the gelatine in water while you make the filling. Tip the ricotta into a bowl, then beat in the peanut butter and syrup. Ricotta has a slightly grainy texture so blitz until smooth with a stick blender for a smoother texture if you prefer.\r\nTake the soaked gelatine from the water and squeeze dry. Put it into a pan with the milk and heat very gently until the gelatine dissolves. Beat into the peanut mixture, then tip onto the biscuit base. Chill until set.\r\nTo freeze, leave in the tin and as soon as it is solid, cover the surface with cling film, then wrap the tin with cling film and foil.\r\nTo defrost, thaw in the fridge overnight.\r\nTo serve, carefully remove from the tin. Whisk the cream with the sugar until it holds its shape, then spread on top of the cheesecake and scatter with the peanut brittle.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/qtuuys1511387068.jpg",
        "strTags": "Cake,Desert,Treat,UnHealthy,Speciality",
        "strYoutube": "https://www.youtube.com/watch?v=QSTsturcyL0",
        "strIngredient1": "Butter",
        "strIngredient2": "Peanut Cookies",
        "strIngredient3": "Gelatine Leafs",
        "strIngredient4": "Ricotta",
        "strIngredient5": "Peanut Butter",
        "strIngredient6": "Golden Syrup",
        "strIngredient7": "Milk",
        "strIngredient8": "Double Cream",
        "strIngredient9": "Light Brown Soft Sugar",
        "strIngredient10": "Peanut Brittle",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "50g",
        "strMeasure2": "175g",
        "strMeasure3": "5",
        "strMeasure4": "500g",
        "strMeasure5": "175g",
        "strMeasure6": "175g",
        "strMeasure7": "150ml",
        "strMeasure8": "275ml",
        "strMeasure9": "2 tblsp ",
        "strMeasure10": "Crushed",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbcgoodfood.com/recipes/1759649/peanut-butter-cheesecake",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }
]

const category = [
    {
        "id": "1",
        "category": "Beef",
        "image": require('../assets/category/beef.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Beef"
    },
    {
        "id": "2",
        "category": "Breakfast",
        "image": require('../assets/category/breakfast.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Breakfast"
    },
    {
        "id": "3",
        "category": "Chicken",
        "image": require('../assets/category/chicken.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Chicken"
    },
    {
        "id": "4",
        "category": "Dessert",
        "image": require('../assets/category/desert.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Dessert"
    },
    {
        "id": "5",
        "category": "Goat",
        "image": require('../assets/category/goat.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Goat"
    },
    {
        "id": "6",
        "category": "Lamb",
        "image": require('../assets/category/lamb.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Lamb"
    },
    {
        "id": "7",
        "category": "Pasta",
        "image": require('../assets/category/pasta.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Pasta"
    },
    {
        "id": "8",
        "category": "Pork",
        "image": require('../assets/category/pork.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Pork"
    },
    {
        "id": "9",
        "category": "Seafood",
        "image": require('../assets/category/seafood.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Seafood"
    },
    {
        "id": "10",
        "category": "Side",
        "image": require('../assets/category/side.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Side"
    },
    {
        "id": "11",
        "category": "Starter",
        "image": require('../assets/category/starter.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Starter"
    },
    {
        "id": "12",
        "category": "Vegan",
        "image": require('../assets/category/vegan.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Vegan"
    },
    {
        "id": "13",
        "category": "Vegetarian",
        "image": require('../assets/category/vegetarian.jpg'),
        "api": "https://www.themealdb.com/api/json/v1/1/filter.php?c=Vegetarian"
    }
]

export {data, category}